name: user_repository
description: Dart package which manages the users
version: 1.0.0

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "^0.5.0"
  firebase_auth: "^0.18.0+1"
  cloud_firestore: ^0.14.0+2
  freezed_annotation: 
  riverpod: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
  freezed: 
  build_runner:
  json_serializable: 
  lint: ^1.2.0

